# Generated by Django 5.1.1 on 2024-09-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
